import matplotlib.pyplot as plt
import seaborn as sns
from wordcloud import WordCloud
from sklearn.decomposition import PCA
from sklearn.manifold import TSNE
from sklearn.cluster import KMeans
import numpy as np
from PIL import Image

def plot_word_cloud(wordcloud):
    """
    Plot the word cloud.
    """
    plt.figure(figsize=(8, 6))
    plt.imshow(wordcloud, interpolation='bilinear')
    plt.axis("off")
    plt.close()  # Close the plot to avoid UI blocking
    return wordcloud

def plot_side_by_side_word_cloud(wordcloud1, wordcloud2):
    """
    Plot two word clouds side by side for comparison.
    """
    fig, axes = plt.subplots(1, 2, figsize=(16, 8))

    axes[0].imshow(wordcloud1, interpolation='bilinear')
    axes[0].axis("off")
    axes[0].set_title("Quran Word Cloud")

    axes[1].imshow(wordcloud2, interpolation='bilinear')
    axes[1].axis("off")
    axes[1].set_title("Bible Word Cloud")

    plt.tight_layout()
    plt.close()  # Close the plot to avoid UI blocking
    return fig

def plot_word_hierarchy(quran_hierarchy, bible_hierarchy, quran_root_word, bible_root_word):
    """
    Plot the hierarchy of related words for Quran and Bible.
    """
    fig, axes = plt.subplots(1, 2, figsize=(16, 8))

    axes[0].barh(range(len(quran_hierarchy[0])), [len(level) for level in quran_hierarchy], color="green")
    axes[0].set_title(f"Quran Word Hierarchy for '{quran_root_word}'")

    axes[1].barh(range(len(bible_hierarchy[0])), [len(level) for level in bible_hierarchy], color="blue")
    axes[1].set_title(f"Bible Word Hierarchy for '{bible_root_word}'")

    plt.tight_layout()
    plt.close()
    return fig

def plot_tsne(embeddings, labels):
    """
    Plot t-SNE visualization of Word2Vec embeddings.
    """
    tsne = TSNE(n_components=2, random_state=42)
    tsne_result = tsne.fit_transform(embeddings)

    plt.figure(figsize=(10, 8))
    plt.scatter(tsne_result[:, 0], tsne_result[:, 1], c='blue', marker='o')
    for i, label in enumerate(labels):
        plt.annotate(label, (tsne_result[i, 0], tsne_result[i, 1]))

    plt.title("t-SNE Visualization of Word2Vec Embeddings")
    plt.close()
    return plt

def plot_pca(embeddings, labels):
    """
    Plot PCA visualization of Word2Vec embeddings.
    """
    pca = PCA(n_components=2)
    pca_result = pca.fit_transform(embeddings)

    plt.figure(figsize=(10, 8))
    plt.scatter(pca_result[:, 0], pca_result[:, 1], c='orange', marker='o')
    for i, label in enumerate(labels):
        plt.annotate(label, (pca_result[i, 0], pca_result[i, 1]))

    plt.title("PCA Visualization of Word2Vec Embeddings")
    plt.close()
    return plt

def plot_kmeans_clustering(embeddings, n_clusters=3):
    """
    Plot KMeans clustering of Word2Vec embeddings.
    """
    kmeans = KMeans(n_clusters=n_clusters, random_state=42)
    kmeans.fit(embeddings)
    labels = kmeans.labels_

    plt.figure(figsize=(10, 8))
    plt.scatter(embeddings[:, 0], embeddings[:, 1], c=labels, cmap="viridis")
    plt.title(f"KMeans Clustering of Word2Vec Embeddings (n_clusters={n_clusters})")
    plt.close()
    return plt

def save_plot_as_image(plot_function, save_path):
    """
    Save the plot generated by a function as an image file.
    """
    plot_function()
    plt.savefig(save_path, bbox_inches='tight')
    plt.close()

def plot_side_by_side_word_cloud_image(wordcloud1_path, wordcloud2_path):
    """
    Plot two word clouds side by side for comparison, loading from file paths.
    """
    wordcloud1 = Image.open(wordcloud1_path)
    wordcloud2 = Image.open(wordcloud2_path)

    fig, axes = plt.subplots(1, 2, figsize=(16, 8))

    axes[0].imshow(wordcloud1, interpolation='bilinear')
    axes[0].axis("off")
    axes[0].set_title("Quran Word Cloud")

    axes[1].imshow(wordcloud2, interpolation='bilinear')
    axes[1].axis("off")
    axes[1].set_title("Bible Word Cloud")

    plt.tight_layout()
    plt.close()  # Close to avoid blocking UI
    return fig
